<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["admin/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["admin/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Username</th>
            <th>Password</th>
            <th>Salt</th>
            <th>Realname</th>
            <th>Phone Of Number</th>
            <th>Intro</th>
            <th>Status</th>
            <th>Creater</th>
            <th>Create Of Ip</th>
            <th>Create Of Time</th>
            <th>Updater</th>
            <th>Update Of Time</th>
            <th>Role</th>
            <th>Grade</th>
            <th>Email</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $admin): ?>
            <tr>
                <td><?php echo $admin->id ?></td>
            <td><?php echo $admin->username ?></td>
            <td><?php echo $admin->password ?></td>
            <td><?php echo $admin->salt ?></td>
            <td><?php echo $admin->realname ?></td>
            <td><?php echo $admin->phone_number ?></td>
            <td><?php echo $admin->intro ?></td>
            <td><?php echo $admin->status ?></td>
            <td><?php echo $admin->creater ?></td>
            <td><?php echo $admin->create_ip ?></td>
            <td><?php echo $admin->create_time ?></td>
            <td><?php echo $admin->updater ?></td>
            <td><?php echo $admin->update_time ?></td>
            <td><?php echo $admin->role_id ?></td>
            <td><?php echo $admin->grade ?></td>
            <td><?php echo $admin->email ?></td>

                <td><?php echo $this->tag->linkTo(["admin/edit/" . $admin->id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["admin/delete/" . $admin->id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("admin/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("admin/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("admin/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("admin/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
